---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy-depl
spec:
  selector:
    matchLabels:
      app: reverse-proxy-depl
  template:
    metadata:
      labels:
        app: reverse-proxy-depl
    spec:
      containers:
      - name: reverse-proxy-depl
        image: nutaro/nginx_frontend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-svc
spec:
  selector:
    app: reverse-proxy-depl
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80